- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
    - name: set stats 
      set_stats:
        data:
          msg: "Hello World!"
